[package]
name = "blog"
version = "0.1.0"
authors = ["piaoliu <441594700@qq.com>"]

[dependencies]
 dotenv = "^0.9.0"
 serde = "^1.0.17"
 serde_json = "^1.0.5"
 serde_derive = "^1.0.17"
 sapper = "^0.1"
 sapper_std = "^0.1"

[dependencies.diesel]
features = ["postgres", "chrono"]
version = "^0.16.0"

[dependencies.chrono]
features = ["serde"]
version = "^0.4.0"

[dependencies.diesel_codegen]
features = ["postgres"]
version = "^0.16.0"
